DROP DATABASE IF EXISTS Presty;
CREATE DATABASE Presty;
USE Presty;


CREATE TABLE `User`(
	ID INT(9) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL,
	USER_TYPE ENUM ('Cliente','Financiera','Autorizador','Administrador') DEFAULT 'Cliente',
	BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No'
);

CREATE TABLE Client(
	ID INT(9) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_USER INT(9) UNSIGNED NOT NULL,
	NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR(45) NOT NULL,
	DNI INT(8) NOT NULL,
	BIRTH_DAY DATE NOT NULL,
	BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No',
	PHONE INT(10) NOT NULL,

	FOREIGN KEY (FK_USER) REFERENCES `User`(ID)
);

CREATE TABLE Financiera(
	ID INT(9) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_USER INT(9) UNSIGNED NOT NULL,
	COMPANY VARCHAR(45) NOT NULL,
	BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No',
	
	FOREIGN KEY (FK_USER) REFERENCES `User`(ID)
);

CREATE TABLE Prestamo(
	ID INT(9) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_CLIENT INT(9) UNSIGNED NOT NULL,
	FK_FINANCIERA INT(9) UNSIGNED NOT NULL,
	FK_AUTORIZADOR INT(9) UNSIGNED NOT NULL,
	AMOUNT INT(11) NOT NULL,
	`STATE` ENUM('Pedido','Pre-Otorgado','Otorgado','Denegado') DEFAULT 'Pedido',
	CREATED_DATE DATETIME NOT NULL,
	BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No',
	
	FOREIGN KEY (FK_CLIENT) REFERENCES Client(ID),
	FOREIGN KEY (FK_FINANCIERA) REFERENCES Financiera(ID),
	FOREIGN KEY (FK_AUTORIZADOR) REFERENCES `User`(ID)
);

CREATE TABLE Publicidad(
	ID INT(9) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(45) NOT NULL,
	LINK VARCHAR(255) NOT NULL,
	IMG VARCHAR(255) NOT NULL,
	BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No'
	
);

CREATE TABLE Veraz(
	ID INT(9) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_PRESTAMO INT(9) UNSIGNED NOT NULL,
	ANSWER ENUM('Aprobado','Reprobado') DEFAULT 'Reprobado',
	
	FOREIGN KEY (FK_PRESTAMO) REFERENCES Prestamo(ID)
);




